"""Initial migration

Revision ID: 263ed33d4a2e
Revises: 7ffd08cb3bc4
Create Date: 2025-04-03 15:27:46.456754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263ed33d4a2e'
down_revision: Union[str, None] = '7ffd08cb3bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_shit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'is_shit')
    # ### end Alembic commands ###
