"""Initial migration

Revision ID: 4d55f55a957d
Revises: 0986d09cfd05
Create Date: 2025-04-03 16:11:11.931074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d55f55a957d'
down_revision: Union[str, None] = '0986d09cfd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('teaching_design_version', sa.Column('recommendation_score', sa.Float(), nullable=True, comment='推荐指数(0-100分)'))
    op.alter_column('teaching_design_version', 'version',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teaching_design_version', 'version',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('teaching_design_version', 'recommendation_score')
    op.drop_column('question', 'is_public')
    # ### end Alembic commands ###
