"""Initial migration

Revision ID: 556de91f7bcd
Revises: 0986d09cfd05
Create Date: 2025-04-03 16:52:39.908539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556de91f7bcd'
down_revision: Union[str, None] = '0986d09cfd05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaching_design_version', sa.Column('level', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaching_design_version', 'level')
    # ### end Alembic commands ###
