"""Initial migration

Revision ID: c03ac831453e
Revises: eece7f4eb025
Create Date: 2025-04-09 20:37:21.021271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c03ac831453e'
down_revision: Union[str, None] = 'eece7f4eb025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teaching_design', sa.Column('input', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teaching_design', 'input')
    # ### end Alembic commands ###
